goal_s:
  x: 1.72
  y: 1.54
  w: 20
  photo_name: 'goal_s.png'

goal_r:
  x: 3.57
  y: 3.16
  w: 20
  photo_name: 'goal_r.png'

goal_l:
  x: 3.2
  y: 3.15
  w: 20
  photo_name: 'goal_l.png'

goal_t:
  x: 5.39
  y: 3
  w: 180
  photo_name: 'goal_t.png'

img_topic: '/usb_cam/image_raw'
